### ISSUE TITLE
Link to aurelia-twbootstrap-plugin broken

### ISSUE THREAD

**Issue by AnderssonPeter** [aurelia-ui-toolkits/issues#8]
the start page has a link to https://github.com/aurelia-ui-toolkits/aurelia-twbootstrap-plugin and it leads to 404

**Comment by adriatic** [comment]
> the start page has a link to ...

The start page of what, please?

**Comment by AnderssonPeter** [comment]
Sorry i ment te Readme.md

**Comment by adriatic** [comment]
Can you please be more specific and either supply a screen shot with the highlighted link that is broken, or the url of the page with that link?

**Comment by JeroenVinke** [comment]
@adriatic I believe he means the README.md of the repository where this issue lives: https://github.com/aurelia-ui-toolkits/issues

**Comment by adriatic** [comment]
Thank you @JeroenVinke - that is clearly what Peter meant and I will handle it right away.

**Comment by adriatic** [comment]
Fixed.
