### ISSUE TITLE
Including Material Design Lite

### ISSUE THREAD

**Issue by apawsey** [aurelia-ui-toolkits/issues#9]
HI,

I've started using MDL in an Aurelia app, and adapting it play nicely.  I'd like to move it forward to a full "bridge" as with approach here, and I'd like to if you would welcome the addition of a new ui toolkit to the collection?

Thanks.

**Comment by adriatic** [comment]
Hi @apawsey - We would be delighted to add you to the team and MDL to our bridges collection. Let me provision you with a repo, chat-room and references to our internal documentation.

**Comment by adriatic** [comment]
Hi @apawsey 

Provisioning done:
1. repository: https://github.com/aurelia-ui-toolkits/aurelia-mdl-bridge. Note that this repository is preloaded with our **[plugin builder](https://github.com/aurelia-ui-toolkits/plugin-builder)** infrastructure, which will *_help you a lot_ at starting the project development
2. related gitter chatroom: https://gitter.im/aurelia-ui-toolkits/aurelia-mdl-bridge

**Comment by adriatic** [comment]
The sentence

> Note that this repository is preloaded with our **plugin builder** infrastructure, which will *help you a lot at starting the project development

was meant to be

> Note that this repository is preloaded with our **bridge skeleton** infrastructure, which will *help you a lot at starting the project development.

#### Fixed
